import { applyAction } from "$app/forms";
import {
	categoryRegex,
	CreateFormError,
	httpRegex,
	ShortcutFormError,
	internalUrlRegex
} from "$lib";
import { goto } from "$app/navigation";
import type { ActionResult } from "@sveltejs/kit";

export const validatePostForm = (formData: FormData) => {
	const url = formData.get("url")?.toString();
	const description = formData.get("description")?.toString();
	const body = formData.get("body")?.toString();
	const unlisted = formData.get("unlisted") ? true : false;

	const selectedCategory = formData.get("selectedCategory")?.toString();
	const customCategory = formData.get("customCategory")?.toString();
	const category = customCategory || selectedCategory;

	const data = {
		url,
		category,
		description,
		body,
		unlisted
	};

	// Filter out all the required params
	if (!url) return { status: 400, error: CreateFormError.missingUrl, data };
	if (!body) return { status: 400, error: CreateFormError.missingBody, data };
	if (!category) {
		return {
			status: 400,
			error: CreateFormError.missingCategory,
			data
		};
	}

	// filter out incorrect formatting
	if (!categoryRegex.test(category)) {
		return { status: 400, error: CreateFormError.invalidCategory, data };
	}
	if (!internalUrlRegex.test(url)) {
		return { status: 400, error: CreateFormError.invalidUrl, data };
	}
	return { status: 200, error: undefined, data };
};

export const validateShortcutForm = (formData: FormData) => {
	const shortcutName = formData.get("name")?.toString().trim();
	const destination = formData.get("destination")?.toString().trim();
	const autoGenerated = !!formData.get("autoGenerated");
	const aliases = formData.get("aliases")?.toString().split(",");

	const data = {
		shortcutName,
		destination,
		autoGenerated,
		aliases
	};

	// Filter out all the required params
	if (!shortcutName) return { status: 400, error: ShortcutFormError.missingName, data };
	if (!destination) return { status: 400, error: ShortcutFormError.missingDestination, data };

	// filter out incorrect formatting
	if (!internalUrlRegex.test(shortcutName)) {
		return { status: 400, error: ShortcutFormError.invalidName, data };
	}
	if (!httpRegex.test(destination)) {
		return { status: 400, error: ShortcutFormError.invalidDestination, data };
	}
	let filteredAliases = aliases?.flatMap((alias) =>
		internalUrlRegex.test(alias) ? alias.toLowerCase().trim() : []
	);
	return { status: 200, error: undefined, data };
};

export const validateShortcutFormEnhanced = (
	formData: FormData,
	cancel: () => void
): {
	error?: ShortcutFormError;
	submit?: ({ result }: { result: ActionResult }) => Promise<void>;
} => {
	const validateResult = validateShortcutForm(formData);
	if (validateResult.error) cancel();

	return {
		submit: async ({ result }: { result: ActionResult }) => {
			// `result` is an `ActionResult` object
			if (result.type === "redirect") {
				goto(result.location);
			} else {
				await applyAction(result);
			}
		},
		...validateResult
	};
};

export const validatePostFormEnhanced = (formData: FormData, cancel: () => void) => {
	let validateResult = validatePostForm(formData);
	if (validateResult.error) cancel();

	return {
		submit: async ({ result }: { result: ActionResult }) => {
			// `result` is an `ActionResult` object
			if (result.type === "redirect") {
				goto(result.location);
			} else {
				await applyAction(result);
			}
		},
		...validateResult
	};
};
