-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_Shortcut" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "shortcut" TEXT NOT NULL,
    "redirectUrl" TEXT NOT NULL,
    "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO "new_Shortcut" ("createdAt", "id", "redirectUrl", "shortcut", "updatedAt") SELECT "createdAt", "id", "redirectUrl", "shortcut", "updatedAt" FROM "Shortcut";
DROP TABLE "Shortcut";
ALTER TABLE "new_Shortcut" RENAME TO "Shortcut";
CREATE UNIQUE INDEX "Shortcut_shortcut_key" ON "Shortcut"("shortcut");
CREATE UNIQUE INDEX "Shortcut_redirectUrl_key" ON "Shortcut"("redirectUrl");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
