<script lang="ts">
	import IconButton from "$lib/components/buttons/IconButton.svelte";
	import ShortcutBox from "$lib/components/ShortcutBox.svelte";
	import type { PageData } from "./$types";

	const { data }: { data: PageData } = $props();
	const shortcuts = $derived(data.shortcuts);
	const manualShortcuts = $derived(
		shortcuts
			.filter((shortcut) => !shortcut.autoGenerated)
			.sort((a, b) => a.shortcut.localeCompare(b.shortcut))
	);
	const autoShortcuts = $derived(
		shortcuts
			.filter((shortcut) => shortcut.autoGenerated)
			.sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime())
	);

	let namedCollapsed = $state(false);
	let autoCollapsed = $state(false);
</script>

<div class="group/type mx-auto my-8 grid grid-cols-1 gap-2">
	<div
		class="transition-all duration-200 ease-in-out group-hover/type:scale-99 group-hover/type:opacity-75 hover:scale-100 hover:opacity-100"
	>
		<div class="flex justify-between px-6">
			<p class="text-center font-bold">Named Shortcuts (alphabetical)</p>
			<IconButton
				class="border-0 bg-transparent"
				icon={namedCollapsed ? "down" : "up"}
				onclick={() => (namedCollapsed = !namedCollapsed)}
			></IconButton>
		</div>
		<div
			class="group/list mx-2 grid grid-cols-1 gap-2 *:w-full md:mr-2 md:grid-cols-2 lg:grid-cols-3"
			hidden={namedCollapsed}
		>
			{#each manualShortcuts as shortcut (shortcut.shortcut)}
				<ShortcutBox {shortcut} />
			{:else}
				<span class="text-center text-secondary-text">nothing seems to be here...</span>
			{/each}
		</div>
	</div>
	<div
		class="transition-all duration-200 ease-in-out group-hover/type:scale-99 group-hover/type:opacity-75 hover:scale-100 hover:opacity-100"
	>
		<div class="flex justify-between px-6">
			<p class="text-center font-bold">Auto Shortcuts (newest to oldest)</p>
			<IconButton
				class="border-0 bg-transparent"
				icon={autoCollapsed ? "down" : "up"}
				onclick={() => (autoCollapsed = !autoCollapsed)}
			></IconButton>
		</div>
		<div
			class="group/list mx-2 grid grid-cols-1 gap-2 *:w-full md:mr-2 md:grid-cols-2 lg:grid-cols-3"
			hidden={autoCollapsed}
		>
			{#each autoShortcuts as shortcut (shortcut.shortcut)}
				<ShortcutBox {shortcut} />
			{:else}
				<span class="text-center text-secondary-text">nothing seems to be here...</span>
			{/each}
		</div>
	</div>
</div>
