<script lang="ts">
	import ShortcutBox from "../../../components/ShortcutBox.svelte";
	import type { PageData } from "./$types";

	let { data }: { data: PageData } = $props();
	let shortcuts = $derived(data.shortcuts);
	let manualShortcuts = $derived(shortcuts.filter((shortcut) => !shortcut.autoGenerated));
	let autoShortcuts = $derived(shortcuts.filter((shortcut) => shortcut.autoGenerated));
</script>

<div class="group/type mx-auto my-8 grid grid-cols-1 gap-2 md:grid-cols-2">
	<div
		class="transition-all duration-200 ease-in-out group-hover/type:scale-99 group-hover/type:opacity-75 hover:scale-100 hover:opacity-100"
	>
		<p class="text-center font-bold">Named Shortcuts</p>
		<div class="group/list mx-2 flex flex-col gap-2 *:w-full md:mr-2">
			{#each manualShortcuts as shortcut (shortcut.shortcut)}
				<ShortcutBox {shortcut} />
			{:else}
				<span class="text-center text-secondary-text">nothing seems to be here...</span>
			{/each}
		</div>
	</div>
	<div
		class="transition-all duration-200 ease-in-out group-hover/type:scale-99 group-hover/type:opacity-75 hover:scale-100 hover:opacity-100"
	>
		<p class="text-center font-bold">Auto Shortcuts</p>
		<div class="group/list mx-2 flex flex-col gap-2 *:w-full md:mr-2">
			{#each autoShortcuts as shortcut (shortcut.shortcut)}
				<ShortcutBox {shortcut} />
			{:else}
				<span class="text-center text-secondary-text">nothing seems to be here...</span>
			{/each}
		</div>
	</div>
</div>
