<script lang="ts">
	import { enhance } from "$app/forms";
	import { ShortcutFormError, simpleHash, urlRegex } from "$lib";
	import BaseModal from "./BaseModal.svelte";
	import { validateShortcutFormClient } from "$lib/formValidation";
	import ConfirmButton from "../buttons/ConfirmButton.svelte";
	import CancelButton from "../buttons/CancelButton.svelte";
	import { invalidateAll } from "$app/navigation";
	import { page } from "$app/state";

	let textParams = page.url.searchParams.get("text")?.trim();
	let titleParams = page.url.searchParams.get("title")?.trim();

	let { showModal = $bindable() }: { showModal: boolean } = $props();

	// These 3 lines make sharing to the PWA work
	let textParamsIsValid = !!(textParams && urlRegex.test(textParams));
	let destination = $state(textParamsIsValid && textParams ? textParams : "");
	let auto = $state(textParamsIsValid);

	const shortcutAuto = $derived(
		btoa(simpleHash(destination).toString()).replaceAll("=", "").toLowerCase()
	);

	let shortcutName: string = $derived(auto ? shortcutAuto : "");

	const completeUrl = $derived("kopymatic.com/quick/" + shortcutName);
	const completeFyiUrl = $derived("kopy.fyi/" + shortcutName);

	let error: ShortcutFormError | undefined = $state(undefined);

	const copyToClipboard = () => {
		navigator.clipboard.writeText(completeFyiUrl);
	};
</script>

<BaseModal hideWhenUnfocused={false} bind:showModal>
	{`Text: ${textParams} - Title: ${titleParams} \n${textParamsIsValid}\n${destination}\n${auto}`}
	<form
		method="POST"
		action="/shortcut/create?/post"
		class="w-full"
		use:enhance={({ formData, cancel }) => {
			const validation = validateShortcutFormClient(formData, cancel);
			if (validation.error) error = validation.error;
			else {
				//This is jank, but it makes the page update after the form is done. Ill take it
				setTimeout(() => {
					copyToClipboard();
					invalidateAll();
				}, 1000);
				showModal = false;
				return validation.submit;
			}
		}}
	>
		<div class="border-primary bg-secondary box-border max-h-min w-full rounded-md border-2 px-4">
			<span class="mx-auto flex w-min items-center">
				<input
					id="autoGenerated"
					type="checkbox"
					name="autoGenerated"
					class="text-accent focus:ring-accent h-4 w-4 rounded-sm"
					bind:checked={auto}
				/>
				<label for="unlisted" class="ms-2 w-full py-4 text-nowrap">Auto Generate Name?</label></span
			>
		</div>
		<label class:hidden={auto}>
			Shortcut Name
			<br />
			<input
				class="w-full"
				name="name"
				type="text"
				required={true}
				maxlength={64}
				bind:value={shortcutName}
			/>
			{#if error === ShortcutFormError.invalidName || error === ShortcutFormError.missingName}
				<p class="error">{error}</p>
			{/if}
		</label>
		<p class="text-secondary-text">
			Your shortcut will be at {completeUrl} <br />and {completeFyiUrl}
		</p>
		<br />
		<label>
			Destination URL
			<br />
			<input
				class="w-full"
				name="destination"
				type="text"
				placeholder="https://www.example.com/"
				required={true}
				bind:value={destination}
			/>
			{#if error === ShortcutFormError.invalidDestination || error === ShortcutFormError.missingDestination}
				<p class="error">{error}</p>
			{/if}
		</label>
		<div class="mt-5 flex flex-auto gap-2">
			<ConfirmButton class="w-full" text="Create Shortcut"></ConfirmButton>
			<CancelButton
				class="w-full"
				onclick={() => {
					showModal = false;
				}}
			></CancelButton>
		</div>
		{#if error === ShortcutFormError.databaseError}
			<p class="error">{error}</p>
		{/if}
	</form>
	{page.url.toString()}
</BaseModal>

<style>
	input {
		@apply w-full;
	}
</style>
