import { error, fail, redirect } from "@sveltejs/kit";
import type { Actions } from "./$types";
import { prisma } from "$lib/server/database/database";
import { ShortcutFormError } from "$lib";
import { isAdmin } from "$lib/server/isAdmin";
import { validateShortcutForm } from "$lib/formValidation";

export const actions = {
	post: async ({ request, locals }) => {
		const session = await locals.auth();
		if (!session || !isAdmin(session.user?.id)) {
			error(401);
		}

		console.log("recieved post request at /shortcut/create");
		const formData = await request.formData();
		console.log(formData);

		const result = validateShortcutForm(formData);
		if (result.error) {
			fail(result.status, {
				error: result.error,
				reconstructedData: result.data
			});
		}

		const { shortcutName, destination, autoGenerated, aliases } = result.data;
		if (!shortcutName || !destination) {
			console.log("The server validation function fucked up");
			fail(500, {
				error: ShortcutFormError.internalError
			});
			return;
		}

		const shortcut = await prisma.shortcut
			.create({
				data: {
					shortcut: shortcutName.toLowerCase(),
					redirectUrl: destination,
					autoGenerated: autoGenerated,
					aliases
				}
			})
			.catch((error) => fail(500, { error: ShortcutFormError.databaseError, message: error }));
		if (!shortcut) {
			return fail(500, {
				error: ShortcutFormError.databaseError,
				message: "Unknown error with the database."
			});
		}
		redirect(302, `/shortcut/view`);
	}
} satisfies Actions;
