import { error, fail, redirect } from "@sveltejs/kit";
import type { Actions } from "./$types";
import { prisma } from "$lib/server/database/database";
import { ShortcutFormError } from "$lib";
import { validateShortcutCreateFormServer } from "$lib/server/serverFormValidation";
import { isAdmin } from "$lib/server/isAdmin";

export const actions = {
	post: async ({ request, locals }) => {
		const session = await locals.auth();
		if (!session || !isAdmin(session.user?.id)) {
			error(401);
		}

		console.log("recieved post request");
		let formData = await request.formData();

		const result = validateShortcutCreateFormServer(formData);
		if (result.status || result.error) {
			fail(result.status, {
				error: result.error,
				reconstructedData: result.data
			});
		}

		const { shortcutName, destination, autoGenerated } = result.data;
		if (!shortcutName || !destination) {
			console.log("The server validation function fucked up");
			fail(500, {
				error: ShortcutFormError.internalError
			});
			return;
		}

		const post = await prisma.shortcut.create({
			data: { shortcut: shortcutName, redirectUrl: destination, autoGenerated: autoGenerated }
		});
		if (!post) {
			return fail(500, {
				error: ShortcutFormError.databaseError,
				message: "Unknown error with the database."
			});
		}
		redirect(302, `/shortcut/view`);
	}
} satisfies Actions;
