import { categoryRegex, CreateFormError, httpRegex, ShortcutFormError, urlRegex } from '$lib';

export const validateCreateFormServer = (formData: FormData) => {
	let url = formData.get('url')?.toString();
	let description = formData.get('description')?.toString();
	let body = formData.get('body')?.toString();
	let unlisted = formData.get('unlisted') ? true : false;

	let selectedCategory = formData.get('selectedCategory')?.toString();
	let customCategory = formData.get('customCategory')?.toString();
	let category = customCategory || selectedCategory;

	let data = {
		url,
		category,
		description,
		body,
		unlisted
	};

	// Filter out all the required params
	if (!url) return { status: 400, error: CreateFormError.missingUrl, data };
	if (!body) return { status: 400, error: CreateFormError.missingBody, data };
	if (!category) {
		return {
			status: 400,
			error: CreateFormError.missingCategory,
			data
		};
	}

	// filter out incorrect formatting
	if (!categoryRegex.test(category)) {
		return { status: 400, error: CreateFormError.invalidCategory, data };
	}
	if (!urlRegex.test(url)) {
		return { status: 400, error: CreateFormError.invalidUrl, data };
	}
	return { status: undefined, error: undefined, data };
};

export const validateShortcutCreateFormServer = (formData: FormData) => {
	let shortcutName = formData.get('name')?.toString().trim();
	let destination = formData.get('destination')?.toString().trim();
	let autoGenerated = !!formData.get('autoGenerated');

	let data = {
		shortcutName,
		destination,
		autoGenerated
	};

	// Filter out all the required params
	if (!shortcutName) return { status: 400, error: ShortcutFormError.missingName, data };
	if (!destination) return { status: 400, error: ShortcutFormError.missingDestination, data };

	// filter out incorrect formatting
	if (!urlRegex.test(shortcutName)) {
		return { status: 400, error: ShortcutFormError.invalidName, data };
	}
	if (!httpRegex.test(destination)) {
		return { status: 400, error: ShortcutFormError.invalidDestination, data };
	}
	return { status: undefined, error: undefined, data };
};
