import {
	categoryRegex,
	CreateFormError,
	httpRegex,
	ShortcutFormError,
	internalUrlRegex
} from "$lib";

export const validateCreateFormServer = (formData: FormData) => {
	const url = formData.get("url")?.toString();
	const description = formData.get("description")?.toString();
	const body = formData.get("body")?.toString();
	const unlisted = formData.get("unlisted") ? true : false;

	const selectedCategory = formData.get("selectedCategory")?.toString();
	const customCategory = formData.get("customCategory")?.toString();
	const category = customCategory || selectedCategory;

	const data = {
		url,
		category,
		description,
		body,
		unlisted
	};

	// Filter out all the required params
	if (!url) return { status: 400, error: CreateFormError.missingUrl, data };
	if (!body) return { status: 400, error: CreateFormError.missingBody, data };
	if (!category) {
		return {
			status: 400,
			error: CreateFormError.missingCategory,
			data
		};
	}

	// filter out incorrect formatting
	if (!categoryRegex.test(category)) {
		return { status: 400, error: CreateFormError.invalidCategory, data };
	}
	if (!internalUrlRegex.test(url)) {
		return { status: 400, error: CreateFormError.invalidUrl, data };
	}
	return { status: undefined, error: undefined, data };
};

export const validateShortcutCreateFormServer = (formData: FormData) => {
	const shortcutName = formData.get("name")?.toString().trim();
	const destination = formData.get("destination")?.toString().trim();
	const autoGenerated = !!formData.get("autoGenerated");

	const data = {
		shortcutName,
		destination,
		autoGenerated
	};

	// Filter out all the required params
	if (!shortcutName) return { status: 400, error: ShortcutFormError.missingName, data };
	if (!destination) return { status: 400, error: ShortcutFormError.missingDestination, data };

	// filter out incorrect formatting
	if (!internalUrlRegex.test(shortcutName)) {
		return { status: 400, error: ShortcutFormError.invalidName, data };
	}
	if (!httpRegex.test(destination)) {
		return { status: 400, error: ShortcutFormError.invalidDestination, data };
	}
	return { status: undefined, error: undefined, data };
};
