<script lang="ts">
	import type { Shortcut } from "@prisma/client";
	import ContentBox from "./ContentBox.svelte";
	import IconButton from "./buttons/IconButton.svelte";
	import DeleteShortcutModal from "./modals/DeleteShortcutModal.svelte";
	import EditShortcutModal from "./modals/EditShortcutModal.svelte";

	const { shortcut }: { shortcut: Shortcut } = $props();
	const name = shortcut.shortcut;
	const destination = shortcut.redirectUrl;

	const url = new URL(destination);
	const destinationTrimmed = `${url.host}${url.pathname}`;

	let showDeleteModal = $state(false);
	let showEditModal = $state(false);
	let showCopiedTooltip = $state(false);

	// const copyToClipboard = () => {
	// 	navigator.clipboard.writeText(`https://kopy.fyi/${name}`);
	// 	showCopiedTooltip = true;
	// 	setTimeout(() => (showCopiedTooltip = false), 1000);
	// };
	const openShareMenu = () => {
		navigator.share({ url: `https://kopy.fyi/${name}` });
	};
</script>

<ContentBox
	prose
	class="mx-auto  place-content-between duration-50 group-hover/list:scale-97 hover:scale-103 "
>
	<div class="flex justify-between">
		<span class="overflow-hidden text-lg overflow-ellipsis">
			{`${name}`}
		</span>
		<span class="group flex flex-nowrap gap-1">
			<IconButton
				onclick={openShareMenu}
				icon="share"
				class="group-hover:scale-90 hover:scale-110"
			/>
			<!-- This looks like ass but its fine -->
			<div
				class:hidden={!showCopiedTooltip}
				data-tooltip="tooltip"
				class="absolute bottom-full left-1/2 z-50 rounded-lg bg-black px-3 py-1.5 text-sm text-white"
			>
				Copied to clipboard!
			</div>
			{#if !shortcut.autoGenerated}
				<IconButton
					onclick={() => (showEditModal = true)}
					icon="edit"
					class="group-hover:scale-90 hover:scale-110"
				/>
			{/if}
			<IconButton
				onclick={() => (showDeleteModal = true)}
				icon="trash"
				class="group-hover:scale-90 hover:scale-110"
			/>
		</span>
	</div>

	<div title={destination} class="max-w-full overflow-hidden overflow-ellipsis">
		<a target="_blank" rel="noopener noreferrer" href={destination}>{destinationTrimmed}</a>
	</div>
</ContentBox>

<DeleteShortcutModal name={shortcut.shortcut} bind:showModal={showDeleteModal} />
<EditShortcutModal {shortcut} bind:showModal={showEditModal} currentName={shortcut.shortcut} />
